### ISSUE TITLE
Intermittent test fail on BatchMessageTest.testSimpleBatchProducerConsumer

### ISSUE THREAD

**Issue by merlimat** [yahoo/pulsar#13]
Output from Travis build:

```
com.yahoo.pulsar.client.admin.internal.BrokerStatsImpl$$EnhancerByMockitoWithCGLIB$$fb883741@6b353df8
Tests run: 361, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 831.053 sec <<< FAILURE! - in TestSuite
testSimpleBatchProducerConsumer(com.yahoo.pulsar.broker.service.BatchMessageTest)  Time elapsed: 0.306 sec  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [4]
    at com.yahoo.pulsar.broker.service.BatchMessageTest.testSimpleBatchProducerConsumer(BatchMessageTest.java:293)

```

**Comment by radekg** [comment]
FYI: I have not experienced this while working on https://github.com/yahoo/pulsar/pull/26

**Comment by radekg** [comment]
@merlimat I just tried the following pr https://github.com/radekg/pulsar/pull/5/files on this test, modified, changed the `invocationCount`

```java
    @Test(invocationCount = 1000)
    public void testNonBatchCumulativeAckAfterBatchPublish() throws Exception {
      ...
```

and I do not have any failures locally. However, looking at the failure in another random place on the linked PR, I think the intermittent errors are caused by using _sync_ tests on an _async_ code.

**Comment by radekg** [comment]
The next commit passes: https://travis-ci.org/radekg/pulsar/builds/163267361. Slightest blip on the main thread and some tests collapse.

**Comment by merlimat** [comment]
Didn't see this failure in long time, closing for now
