### ISSUE TITLE
Introduce a way to update broker service configuration dynamically

### ISSUE THREAD

**Issue by rdhabalia** [yahoo/pulsar#184]
As discussed at #176 

> We need to think well how to expose the whole thing in consistent way. You have the values from the config file + the values in ZK. There should be a clear way to understand what is the actual configuration that is:
Supposed to be applied to all brokers
It's actually being applied in a given broker...
Other problem is how to clearly identify which values are dynamically tunable (eg: zk servers string will not be dynamic...)

@merlimat @saandrews : I have created very initial level [commit](https://github.com/rdhabalia/pulsar/commit/380c39ccc5836e38a49e0a7f6e67762da12165f1) to propose a possible approach for this feature. Can you please provide your thoughts or ideas on it. If it makes sense then we can move forward on this approach.

**Comment by merlimat** [comment]
Few random ideas (haven't looked at the code yet): 
 * Mark dynamic settings with an annotation in `ServiceConfiguration`
 * Have a way to register for config changes events (this may be useful for certain class of variables)
 * Otherwise, just read the "dirty" value from the `ServiceConfiguration` instance (don't store it in local variable and don't use any mutex
 * Add a REST handle to change key/value pairs, that only accept variables marked as dynamic
 * Store all dynamically configured variables in a single z-node in "properties" format
 * At startup log the content of that z-node and log each time a change is detected

**Comment by rdhabalia** [comment]
* Mark dynamic settings with an annotation in `ServiceConfiguration` : **[Yes, Included in commit]**
 * Have a way to register for config changes events (this may be useful for certain class of variables) **[Yes, Included in commit]**
 * Otherwise, just read the "dirty" value from the `ServiceConfiguration` instance (don't store it in local variable and don't use any mutex **[Have done similar change]**
 * Add a REST handle to change key/value pairs, that only accept variables marked as dynamic **[Yes, Included in commit]**
 * Store all dynamically configured variables in a single z-node in "properties" format **[Yes, Included in commit]**
 * At startup log the content of that z-node and log each time a change is detected **[Yes, Will do]**

This commit includes almost all above suggestions. Once you review and if you think it is fine then I will go ahead and complete full changes.
