### ISSUE TITLE
Pulsar binary releases are not getting uploaded to GitHub as expected

### ISSUE THREAD

**Issue by agarman** [yahoo/pulsar#340]
#### Expected behavior

[GettingStarted](https://github.com/yahoo/pulsar/blob/a86b6df3c54da8f78bd986f2541cd106f031421e/docs/GettingStarted.md#getting-the-software) is no longer accurate.

#### Actual behavior

[Releases](https://github.com/yahoo/pulsar/releases/latest) no longer hosting pulsar-X.Y-bin.tar.gz artifacts.

#### System configuration

Last version with a binary release was 1.16.5.

**Comment by agarman** [comment]
This would be a minor concern except that `mvn test` now fails or takes >2 hours (from 12 minutes 2 days ago).

**Comment by merlimat** [comment]
Bin releases missing is not voluntary.. we need to understand why travis is not pushing the releases anymore. @rdhabalia any idea?

**Comment by rdhabalia** [comment]
I don't see any clear reason why it stopped after 1.17 release but I am still investigating it.

**Comment by rdhabalia** [comment]
@merlimat do you think is there any change in [secure-key](https://github.com/yahoo/pulsar/blob/master/.travis.yml#L39) or we can update if it has been changed.

**Comment by merlimat** [comment]
I didn't do any change in the keys.. also the github oauth token permissions appears to be still correct. I don't understand why it doesn't upload anymore, even though from a build perspective it appears everything is successful. Even on the OAuth status, it says the token was used in the past 5 days.. when the last release was tagged..

I will regenerate the token and upload it to try again. Though it will not work for already released tags anyway. For those, I think we should manually upload the release binaries for now, and verify that gets fixed in next releases.

**Comment by rdhabalia** [comment]
> For those, I think we should manually upload the release binaries for now, and verify that gets fixed in next releases.

Yes, I will upload them.

**Comment by rdhabalia** [comment]
I have manually uploaded binaries to appropriate releases for now.

**Comment by agarman** [comment]
1.17.4 still not publishing binaries.

**Comment by merlimat** [comment]
From the Travis build log : https://s3.amazonaws.com/archive.travis-ci.org/jobs/225491810/log.txt

```
...
[33mPreparing deploy[0m
Logged in as Matteo Merli
Deploying to repo: yahoo/pulsar
Current tag is: v1.17.4
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
Saved working directory and index state WIP on (no branch): dcb80a1 Pulsar release 1.17.4
HEAD is now at dcb80a1 Pulsar release 1.17.4
....
```

I think that some behavior on Travis side might have changed. We didn't have the `skip_cleanup:true` from the github releases, but we should probably add that. 
Otherwise, I have verified that doing the `git stash --all` is getting rid of the generated tgz files

**Comment by merlimat** [comment]
@rdhabalia can you manually upload 1.17.4 binaries? Hopefully for the last time...

**Comment by rdhabalia** [comment]
yes, I was going to do it but then missed it. I will do it.

**Comment by rdhabalia** [comment]
Travis build is now able to upload the binary into release. (verified in 1.17.5) so, closing the issue.
