### ISSUE TITLE
High GC Pause during message redelivery

### ISSUE THREAD

**Issue by jai1** [yahoo/pulsar#398]
#### Expected behavior

Broker GC Pause - young and old should be less than one second.

#### Actual behavior

When redelivery is called by a consumer with a lot of unacked messages we end up creating a lot of temporary objects which lead to high GC in the broker. (Details [here](https://docs.google.com/document/d/1dUMpWHJC9mfC7F7EVK_AurNEPIeAgurhkZygD-33y9g/edit?usp=sharing))

#### Steps to reproduce

a. Keep Redelivery Timeout as 5 mins.
b. Message Production rate - 6K mps over 600 topics
c. Consumer queue size = 10 (in order to keep the delivery rate under control)
d. 16 shared consumers per topic.
e. Ack only 5 -10 % of the messages for an hour.
f. Use only one broker.
g. You will start seeing high GC pauses

#### Plan to mitigate the issue
I will try to make PositionImpl recyclable and if the issue persists we will talk about moving the unacked message tracker to broker side on pending messages queue.

#### System configuration
**Pulsar version**: x.y

**Comment by jai1** [comment]
@rdhabalia @merlimat @saandrews

**Comment by merlimat** [comment]
is that in client or broker?

**Comment by jai1** [comment]
The GC pause happens in the broker.

**Comment by rdhabalia** [comment]
I think main issue here is if property misbehaves in terms of redelivery then right now broker doesn’t have guard to protect it. 
- Recently we have seen that, One of the property has 80 consumers per topic in shared subscription and it intentionally doesn’t ack high percentage of messages back and set the ack-time out 10 minutes (for redelivery) which makes broker to add those message-Positions into messageReply-bucket and redeliver large number of messages to consumers. Now, due to default MAX unacked message limit = 50K at consumer and with 80 consumers broker allowed to dispatch 4million messages per topic and due to ack-time out broker keeps 4 million messages into memory and dispatching them as per consumer consume-rate. Multiple topics with similar behavior causes high gc pause at broker which makes situation even worse and it also cause restart of the broker due to zk-session lost (zk-keep-Alive).
- It happens when client has high number of consumers and follow above unack behavior, and broker doesn’t guard against it. To protect this situation, broker should have unack-message limit at dispatcher level as well to allow N number of message-positions to be present into messageReply-bucket and as these position objects are in limited number, they won't sit in memory long and can avoid old-gc. I will create a PR to control message dispatching at dispatcher same as we have at consumer level.
