### ISSUE TITLE
Reset Consumer on Global Topic

### ISSUE THREAD

**Issue by sschepens** [yahoo/pulsar#73]
#### Expected behavior

It should be allowed to reset a cursor on a global cluster.
Subscriptions are local to a cluster, I don't see how a cursor reset on a global topic would generate problems.

#### Actual behavior

`com.yahoo.pulsar.client.admin.PulsarAdminException$NotAllowedException: reset cursor not supported for global topic`

**Comment by merlimat** [comment]
Yes, I don't remember if there was any specific reason to enforce that condition, but I cannot see any right now. 

https://github.com/yahoo/pulsar/blob/master/pulsar-broker/src/main/java/com/yahoo/pulsar/broker/admin/PersistentTopics.java#L851

As you said, subscriptions are independent for each clusters, and as with other operations (skip, unsubscribe, etc..) they are all performed on the subscription found on the local cluster, rather than everywhere.

**Comment by merlimat** [comment]
Fixed in #79
