### ISSUE TITLE
Intermittent test failure SimpleProducerConsumerTest.testUnackBlockRedeliverMessages

### ISSUE THREAD

**Issue by merlimat** [yahoo/pulsar#93]
Seen it failing a few times with: 

```
testUnackBlockRedeliverMessages(com.yahoo.pulsar.client.api.SimpleProducerConsumerTest)  Time elapsed: 3.166 sec  <<< FAILURE!
java.lang.AssertionError: expected [20] but found [112]
    at com.yahoo.pulsar.client.api.SimpleProducerConsumerTest.testUnackBlockRedeliverMessages(SimpleProducerConsumerTest.java:1301)
```

**Comment by rdhabalia** [comment]
As we had seen earlier in #5 : this test-case was keep failing because [travis](https://travis-ci.org/yahoo/pulsar/builds/170640919) was picking up wrong [commit](https://github.com/yahoo/pulsar/commit/1b99fa608daa42955e09356f89ae498d6c969347). Closing this issue for now as we haven't seen this failure after that.
